### ISSUE TITLE
发送图片会报错

### ISSUE THREAD

**Issue by AliceNEET** [lgc2333/py-xlz-http-v2#5]
## 环境
python 3.8
requests           2.26.0   
tornado            6.1
urllib3            1.26.7

使用的是tornado_http.py

## 错误
![Snipaste_2021-10-13_12-42-28](https://user-images.githubusercontent.com/20288016/137068715-553f6e79-6bb1-4414-8516-a707fe579be7.png)

## 尝试解决
print j中的keys

![Snipaste_2021-10-13_12-53-51](https://user-images.githubusercontent.com/20288016/137069747-ecddd03f-046e-40bd-9043-512474b813e9.png)

**Comment by lgc2333** [comment]
应该解决了
